import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { cropBoundingBox } from "./crop.ts";
import { cropBoundingBoxSchema, type CropBoundingBoxInput } from "./schema.ts";

interface PiLike {
  registerTool(tool: {
    name: string;
    label: string;
    description: string;
    promptSnippet?: string;
    promptGuidelines?: string[];
    parameters: unknown;
    execute: (
      toolCallId: string,
      params: CropBoundingBoxInput,
      signal?: AbortSignal,
      onUpdate?: unknown,
      ctx?: { cwd?: string },
    ) => Promise<{ content: Array<{ type: "text"; text: string }>; details?: unknown }>;
  }): void;
}

export interface VisualPrimitivesOptions {
  pluginDir: string;
}

export function registerVisualPrimitives(pi: PiLike | ExtensionAPI, _options: VisualPrimitivesOptions): void {
  pi.registerTool({
    name: "crop_bounding_box",
    label: "Crop Bounding Box",
    description: "Crop an image region from a visual-primitive bounding box. Supports normalized 0-999 and pixel coordinates, top-left and bottom-left origins, padding, and bounds clamping.",
    promptSnippet: "Crop image regions from bounding boxes generated by visual reasoning or provided by the user.",
    promptGuidelines: [
      "Use crop_bounding_box when the user asks to inspect or extract a bounding box region from an image.",
      "crop_bounding_box defaults to visual-primitives normalized 0-999 coordinates; set coordinateSpace to pixel for pixel boxes.",
      "For bottom-left coordinate systems, set crop_bounding_box origin to bottom-left and boxOrder to left-bottom-right-top.",
    ],
    parameters: cropBoundingBoxSchema,
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      const details = await cropBoundingBox(params, { cwd: ctx?.cwd ?? process.cwd(), signal });
      return {
        content: [{
          type: "text",
          text: `Cropped bounding box to ${details.outputPath} (left=${details.resolvedPixelBox.left}, top=${details.resolvedPixelBox.top}, width=${details.resolvedPixelBox.width}, height=${details.resolvedPixelBox.height})`,
        }],
        details,
      };
    },
  });
}

export function pluginDirFromImportMeta(url: string): string {
  return dirname(fileURLToPath(url));
}
